<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tammineni" failures="1" tests="4" name="Test Cases: displayAllUsers, newUser, userValidations, createUser" time="4.834" errors="0" timestamp="19 Nov 2017 16:09:44 GMT">
  <testcase classname="testlogin.mavendependency.AppTest" name="displayAllUsers" time="0.432"/>
  <testcase classname="testlogin.mavendependency.AppTest" name="userValidations" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at testlogin.mavendependency.AppTest.userValidations(AppTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- userValidations -->
  <testcase classname="testlogin.mavendependency.AppTest" name="newUser" time="0.167"/>
  <testcase classname="testlogin.mavendependency.AppTest" name="createUser" time="0.0">
    <skipped/>
  </testcase> <!-- createUser -->
</testsuite> <!-- Test Cases: displayAllUsers, newUser, userValidations, createUser -->
